// Generated by CoffeeScript 2.7.0
var draw, logoFont, logoHitbox, mouseHitbox, setup;

logoFont = null;

logoHitbox = null;

mouseHitbox = null;

// use await not preload()
setup = async function() {
  createCanvas(960, 540);
  await (logoFont = loadFont("assets/bluunext-bold.ttf"));
  logoHitbox = new Hitbox("CENTER", "rectangle", width / 2, height / 2, 585, 80);
  return mouseHitbox = new Hitbox("CENTER", "rectangle", width / 2, height / 2, 1, 1);
};

draw = function() {
  background(25);
  mouseHitbox.update(mouseX, mouseY);
  logoHitbox.update(width / 2, height / 2 - 10);
  fill("white");
  textFont(logoFont);
  textSize(100);
  textAlign(CENTER, MIDDLE);
  text("voidlearning", width / 2, height / 2);
  if (checkCollision(logoHitbox, mouseHitbox)) {
    return cursor(HAND);
  } else {
    return cursor("default");
  }
};
