// Generated by CoffeeScript 2.7.0
var draw, logoFont, logoHitbox, setup;

logoFont = null;

logoHitbox = null;

// use await not preload()
setup = async function() {
  createCanvas(960, 540);
  await (logoFont = loadFont("assets/bluunext-bold.ttf"));
  return logoHitbox = new Hitbox("CENTER", "rectangle", width / 2, height / 2, 100, 100);
};

draw = function() {
  background(25);
  logoHitbox.update(width / 2, height / 2);
  logoHitbox.debug();
  fill("white");
  textFont(logoFont);
  textSize(100);
  textAlign(CENTER, MIDDLE);
  return text("voidmath", width / 2, height / 2);
};
